//! The connection handle. Wraps surql-rs's `DatabaseClient` and owns the
//! configured embedding dimension so repositories and schema agree.

use surql::connection::ConnectionConfig;
use surql::DatabaseClient;

use antumbra_core::Result;

use crate::error::map;
use crate::schema::{self, EMBED_DIM};

#[derive(Clone)]
pub struct Store {
    client: DatabaseClient,
    embed_dim: usize,
}

impl Store {
    /// Connect to an embedded in-memory database and apply the schema. Ideal
    /// for tests and ephemeral runs; nothing persists past process exit.
    pub async fn connect_memory(embed_dim: usize) -> Result<Self> {
        let config = ConnectionConfig::builder()
            .url("mem://")
            .namespace("antumbra")
            .database("main")
            .build()
            .map_err(map)?;
        Self::connect(config, embed_dim).await
    }

    /// Connect to a configured database (remote `ws://` or embedded
    /// `surrealkv://`) and apply the schema.
    pub async fn connect(config: ConnectionConfig, embed_dim: usize) -> Result<Self> {
        let client = DatabaseClient::new(config).map_err(map)?;
        client.connect().await.map_err(map)?;
        let store = Store { client, embed_dim };
        store.ensure_schema().await?;
        Ok(store)
    }

    /// Apply the schema. The statements are generated by surql-rs schema
    /// builders (`schema::schema_statements`) — not hand-authored SurrealQL —
    /// and are idempotent (`IF NOT EXISTS`), so this is safe to call repeatedly.
    pub async fn ensure_schema(&self) -> Result<()> {
        let script = schema::schema_statements(self.embed_dim as u32)?.join("\n");
        self.client.query(&script).await.map_err(map)?;
        Ok(())
    }

    pub fn embed_dim(&self) -> usize {
        self.embed_dim
    }

    pub(crate) fn client(&self) -> &DatabaseClient {
        &self.client
    }
}

pub const DEFAULT_EMBED_DIM: usize = EMBED_DIM;
