//! The connection handle. Wraps surql-rs's `DatabaseClient` and owns the
//! configured embedding dimension so repositories and schema agree.

use surql::connection::auth::{RootCredentials, ScopeCredentials};
use surql::connection::ConnectionConfig;
use surql::DatabaseClient;

use antumbra_core::{Result, TenantId, UserId};

use crate::error::map;
use crate::schema::{self, EMBED_DIM, TENANT_ACCESS};

#[derive(Clone)]
pub struct Store {
    client: DatabaseClient,
    embed_dim: usize,
    namespace: String,
    database: String,
}

impl Store {
    /// Connect to an embedded in-memory database and apply the schema. Ideal
    /// for tests and ephemeral runs; nothing persists past process exit.
    pub async fn connect_memory(embed_dim: usize) -> Result<Self> {
        let config = ConnectionConfig::builder()
            .url("mem://")
            .namespace("antumbra")
            .database("main")
            .build()
            .map_err(map)?;
        Self::connect(config, embed_dim).await
    }

    /// Connect to a configured database (remote `ws://` or embedded
    /// `surrealkv://`) and apply the schema.
    pub async fn connect(config: ConnectionConfig, embed_dim: usize) -> Result<Self> {
        let store = Self::connect_without_schema(config, embed_dim).await?;
        store.ensure_schema().await?;
        Ok(store)
    }

    /// Connect **without** applying the schema. For a second, credential-less
    /// *serving* connection to an authenticated remote whose schema a root
    /// connection has already applied: an anonymous session cannot run `DEFINE`,
    /// and only needs to sign in per request as a record (which then scopes the
    /// engine ACL correctly — unlike a root connection, which bypasses it). See
    /// the R-6 fix in the MCP HTTP layer.
    pub async fn connect_without_schema(
        config: ConnectionConfig,
        embed_dim: usize,
    ) -> Result<Self> {
        let namespace = config.namespace().to_string();
        let database = config.database().to_string();
        let client = DatabaseClient::new(config).map_err(map)?;
        client.connect().await.map_err(map)?;
        Ok(Store {
            client,
            embed_dim,
            namespace,
            database,
        })
    }

    /// Authenticate this session as `(tenant, user)` via the record-access
    /// method, so `$auth.tenant` (the hard isolation key) and `$auth.user` (the
    /// compartment-ownership / sharing actor) are bound and the engine enforces
    /// the row-level PERMISSIONS. Requires a provisioned principal. Root/owner
    /// sessions skip this and see across tenants.
    pub async fn signin(&self, tenant: &TenantId, user: &UserId) -> Result<()> {
        let creds = ScopeCredentials::new(&self.namespace, &self.database, TENANT_ACCESS)
            .with("tenant", tenant.as_str())
            .with("user", user.as_str());
        self.client.signin(&creds).await.map_err(map)?;
        Ok(())
    }

    /// Drop the current session's authentication, returning to the owner/root
    /// view (full access on the embedded engine).
    pub async fn invalidate(&self) -> Result<()> {
        self.client.invalidate().await.map_err(map)?;
        Ok(())
    }

    /// Return to the **owner/root** view for cross-tenant work (provisioning a
    /// principal, the live-propagation watcher). On an authenticated remote
    /// (`ws://` with root credentials) this re-signs-in as root, because there
    /// `invalidate` would drop to *anonymous* — which has no permissions. On an
    /// embedded/unauthenticated store (no configured credentials) it falls back
    /// to `invalidate` (anonymous *is* the owner there). Use this, not
    /// `invalidate`, whenever owner access is required on a real deployment.
    pub async fn signin_root(&self) -> Result<()> {
        match (
            self.client.config().username(),
            self.client.config().password(),
        ) {
            (Some(user), Some(pass)) => {
                let creds = RootCredentials::new(user, pass);
                self.client.signin(&creds).await.map_err(map)?;
            }
            _ => self.client.invalidate().await.map_err(map)?,
        }
        Ok(())
    }

    /// Apply the schema. The statements are generated by surql-rs schema
    /// builders (`schema::schema_statements`) — not hand-authored SurrealQL —
    /// and are idempotent (`IF NOT EXISTS`), so this is safe to call repeatedly.
    pub async fn ensure_schema(&self) -> Result<()> {
        let script = schema::schema_statements(self.embed_dim as u32)?.join("\n");
        self.client.query(&script).await.map_err(map)?;
        Ok(())
    }

    pub fn embed_dim(&self) -> usize {
        self.embed_dim
    }

    pub(crate) fn client(&self) -> &DatabaseClient {
        &self.client
    }
}

pub const DEFAULT_EMBED_DIM: usize = EMBED_DIM;

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn embedded_store_reports_its_dim_and_owner_access_falls_back() {
        let store = Store::connect_memory(EMBED_DIM).await.unwrap();
        assert_eq!(store.embed_dim(), EMBED_DIM);
        // On an embedded store there are no configured credentials, so owner
        // access (`signin_root`) takes the `invalidate` fallback — anonymous *is*
        // the owner there. Both are no-ops here but must not error.
        store.signin_root().await.unwrap();
        store.invalidate().await.unwrap();
        // Schema application is idempotent — safe to re-run.
        store.ensure_schema().await.unwrap();
    }
}
