//! The connection handle. Wraps surql-rs's `DatabaseClient` and owns the
//! configured embedding dimension so repositories and schema agree.

use surql::connection::auth::ScopeCredentials;
use surql::connection::ConnectionConfig;
use surql::DatabaseClient;

use antumbra_core::{Result, TenantId};

use crate::error::map;
use crate::schema::{self, EMBED_DIM, TENANT_ACCESS};

#[derive(Clone)]
pub struct Store {
    client: DatabaseClient,
    embed_dim: usize,
    namespace: String,
    database: String,
}

impl Store {
    /// Connect to an embedded in-memory database and apply the schema. Ideal
    /// for tests and ephemeral runs; nothing persists past process exit.
    pub async fn connect_memory(embed_dim: usize) -> Result<Self> {
        let config = ConnectionConfig::builder()
            .url("mem://")
            .namespace("antumbra")
            .database("main")
            .build()
            .map_err(map)?;
        Self::connect(config, embed_dim).await
    }

    /// Connect to a configured database (remote `ws://` or embedded
    /// `surrealkv://`) and apply the schema.
    pub async fn connect(config: ConnectionConfig, embed_dim: usize) -> Result<Self> {
        let namespace = config.namespace().to_string();
        let database = config.database().to_string();
        let client = DatabaseClient::new(config).map_err(map)?;
        client.connect().await.map_err(map)?;
        let store = Store {
            client,
            embed_dim,
            namespace,
            database,
        };
        store.ensure_schema().await?;
        Ok(store)
    }

    /// Authenticate this session as `tenant` via the record-access method, so
    /// `$auth.tenant` is bound and the engine enforces the row-level PERMISSIONS
    /// (a tenant session can no longer read another tenant's rows, even with the
    /// app-side WHERE removed). Requires a provisioned principal for the tenant.
    /// Root/owner sessions skip this and see across tenants.
    pub async fn signin_tenant(&self, tenant: &TenantId) -> Result<()> {
        let creds = ScopeCredentials::new(&self.namespace, &self.database, TENANT_ACCESS)
            .with("tenant", tenant.as_str());
        self.client.signin(&creds).await.map_err(map)?;
        Ok(())
    }

    /// Drop the current session's authentication, returning to the owner/root
    /// view (full access on the embedded engine).
    pub async fn invalidate(&self) -> Result<()> {
        self.client.invalidate().await.map_err(map)?;
        Ok(())
    }

    /// Apply the schema. The statements are generated by surql-rs schema
    /// builders (`schema::schema_statements`) — not hand-authored SurrealQL —
    /// and are idempotent (`IF NOT EXISTS`), so this is safe to call repeatedly.
    pub async fn ensure_schema(&self) -> Result<()> {
        let script = schema::schema_statements(self.embed_dim as u32)?.join("\n");
        self.client.query(&script).await.map_err(map)?;
        Ok(())
    }

    pub fn embed_dim(&self) -> usize {
        self.embed_dim
    }

    pub(crate) fn client(&self) -> &DatabaseClient {
        &self.client
    }
}

pub const DEFAULT_EMBED_DIM: usize = EMBED_DIM;
